# Generated by Django 4.2 on 2024-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='emp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
